services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
      - "9229:9229"  
    volumes:
      - .:/app
      - ./cache:/app/cache
      - node_modules:/app/node_modules  
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - CACHE=/app/cache
    command: node --inspect=0.0.0.0:9229 main.js --host 0.0.0.0 --port 3000 --cache /app/cache
